mod commands;
use commands::*;

fn main() {
    let commands: Vec<BashCommand> = vec![
        vec![
            // c1_enable_os_autoupdate(),
            c2_ensure_apple_software_is_current(),
            c3_enable_auto_update(),
            c4_enable_download_new_updates(),
            c5_enable_app_update_installation(),
            c6_1_enable_system_data_files(),
            c6_2_enable_security_updates(),
            c7_1_disable_bluetooth(),
            c7_2_restart_bluetooth_daemon(),
            ],
        c8_show_bluetooth_status(), // Already a Vec<BashCommand>
        vec![
            c9_1_set_timezone(),
            c9_2_set_network_time_server(),
            c9_3_enable_network_time(),
            c10_sync_time()
            ],
        c11_set_screensaver_inactivity_interval(),
        c12_ensure_secure_screensaver_corners(),
        vec![
            c13_disable_remote_apple_events(),
            c14_disable_internet_sharing(),
            c15_disable_screen_sharing(),
            c16_disable_printer_sharing(),
            c17_disable_remote_login(),
            c18_disable_dvd_cd_sharing(),
            c19_disable_file_sharing(),
            c20_disable_remote_management(),
            c21_disable_content_caching(),
            ],
        c22_disable_airdrop(),
        c23_disable_media_sharing(),
        c24_disable_airplay_receiver(),
        vec![
            c25_enable_firewall(),
            c26_enable_firewall_stealth_mode(),
            c27_1_enable_location_services(),
            c27_2_restart_location_services(),
            c28_1_disable_diagnostic_data(),
            ],
        c28_2_disable_diagnostic_data_per_user(),
        c29_enable_limit_ad_tracking(),
        vec![
            c30_enable_gatekeeper(),
            c31_enable_custom_login_message(),
            c32_ensure_admin_password_for_system_preferences(),
            c33_require_password_to_wake(),
            c34_configure_sleep_settings_based_on_cpu(),
            c35_disable_wake_for_network_access(),
            c36_disable_powernap_based_on_cpu(),
            c37_enable_security_auditing(),
            c38_configure_auditing_flags(),
            c39_configure_install_log_retention(),
            c40_configure_auditing_retention(),
            c41_1_chown_audit_control(),
            c41_2_chmod_audit_control(),
            c41_3_chown_var_audit(),
            c41_4_chmod_var_audit(),
            c42_1_enable_logging_mode(),
            c42_2_configure_logging_detail(),
            c43_disable_bonjour_advertising(),
            c44_disable_http_server(),
            c45_disable_nfs_server(),
            ],
        c46_secure_home_folders(),
        vec![
            c47_enable_amfi(),
            c47_1_enable_library_validation(),
            ],
        c48_ensure_permissions_for_system_apps(),
        c49_fix_world_writable_system_files(),
        c50_fix_world_writable_library_files(),
        vec![
            c51_configure_password_account_lockout(),
            c52_configure_password_min_length(),
            c53_configure_password_requires_alpha(),
            c54_configure_password_requires_numeric(),
            c55_configure_password_requires_symbol(),
            c56_configure_password_requires_mixed_case(),
            c57_configure_password_age(),
            c58_configure_password_history(),
            c59_configure_sudo_settings(),
            c60_update_progress(),
            c61_disable_root_account(),
            c62_disable_automatic_login(),
            c63_prevent_admin_login_to_locked_session(),
            c63_1_disable_fast_user_switching(),
        ],
        c64_remove_password_hints(),
        c65_enable_secure_keyboard_entry(),
        vec![
            c66_enable_login_name_password_display(),
            c67_disable_password_hints(),
            c68_disable_guest_account(),
            c69_disable_guest_shared_folders_access(),
            c70_remove_guest_home_folder(),
            ],
        c71_enable_show_all_filename_extensions(),
        c72_disable_auto_open_safe_files(),
        c73_enable_warn_about_fraudulent_websites(),
        c74_enable_cross_site_tracking_prevention(),
        c75_disable_automatic_opening_of_safe_files(),
        c76_disable_private_click_measurement(),
        c77_enable_show_full_website_address(),
        c78_disable_bluetooth_sharing(),
        vec![
            c79_set_login_window_banner(),
            c80_restart_wazuh_agent()            
            ]
        ]
        .into_iter()
        .flatten()
        .collect();

    for i in commands {
        i.execute();
    }

}
